// Code generated by protocolgen; DO NOT EDIT.

package ws

import (
	"fmt"

	"yimsg/internal/appmsg"
	"yimsg/internal/protocol/pb"
	"yimsg/internal/service"

	"google.golang.org/protobuf/proto"
)

// ActionType 把 action 名映射为 type id。
func ActionType(action string) (uint16, bool) {
	switch action {
	case "register":
		return uint16(pb.Type_TYPE_ACTION_REGISTER), true
	case "login":
		return uint16(pb.Type_TYPE_ACTION_LOGIN), true
	case "authenticate":
		return uint16(pb.Type_TYPE_ACTION_AUTHENTICATE), true
	case "logout":
		return uint16(pb.Type_TYPE_ACTION_LOGOUT), true
	case "ping":
		return uint16(pb.Type_TYPE_ACTION_PING), true
	case "update_user_info":
		return uint16(pb.Type_TYPE_ACTION_UPDATE_USER_INFO), true
	case "update_password":
		return uint16(pb.Type_TYPE_ACTION_UPDATE_PASSWORD), true
	case "get_user_infos":
		return uint16(pb.Type_TYPE_ACTION_GET_USER_INFOS), true
	case "search_user":
		return uint16(pb.Type_TYPE_ACTION_SEARCH_USER), true
	case "add_friend":
		return uint16(pb.Type_TYPE_ACTION_ADD_FRIEND), true
	case "accept_friend":
		return uint16(pb.Type_TYPE_ACTION_ACCEPT_FRIEND), true
	case "reject_friend":
		return uint16(pb.Type_TYPE_ACTION_REJECT_FRIEND), true
	case "delete_friend":
		return uint16(pb.Type_TYPE_ACTION_DELETE_FRIEND), true
	case "update_remark":
		return uint16(pb.Type_TYPE_ACTION_UPDATE_REMARK), true
	case "get_contacts":
		return uint16(pb.Type_TYPE_ACTION_GET_CONTACTS), true
	case "get_contact_count":
		return uint16(pb.Type_TYPE_ACTION_GET_CONTACT_COUNT), true
	case "sync_contacts":
		return uint16(pb.Type_TYPE_ACTION_SYNC_CONTACTS), true
	case "favorite_group":
		return uint16(pb.Type_TYPE_ACTION_FAVORITE_GROUP), true
	case "unfavorite_group":
		return uint16(pb.Type_TYPE_ACTION_UNFAVORITE_GROUP), true
	case "block_user":
		return uint16(pb.Type_TYPE_ACTION_BLOCK_USER), true
	case "unblock_user":
		return uint16(pb.Type_TYPE_ACTION_UNBLOCK_USER), true
	case "get_blocklist":
		return uint16(pb.Type_TYPE_ACTION_GET_BLOCKLIST), true
	case "sync_blocklist":
		return uint16(pb.Type_TYPE_ACTION_SYNC_BLOCKLIST), true
	case "send_message":
		return uint16(pb.Type_TYPE_ACTION_SEND_MESSAGE), true
	case "sync_messages":
		return uint16(pb.Type_TYPE_ACTION_SYNC_MESSAGES), true
	case "get_messages":
		return uint16(pb.Type_TYPE_ACTION_GET_MESSAGES), true
	case "delete_message":
		return uint16(pb.Type_TYPE_ACTION_DELETE_MESSAGE), true
	case "get_conversations":
		return uint16(pb.Type_TYPE_ACTION_GET_CONVERSATIONS), true
	case "sync_conversations":
		return uint16(pb.Type_TYPE_ACTION_SYNC_CONVERSATIONS), true
	case "get_unread_count":
		return uint16(pb.Type_TYPE_ACTION_GET_UNREAD_COUNT), true
	case "clear_unread":
		return uint16(pb.Type_TYPE_ACTION_CLEAR_UNREAD), true
	case "delete_conversation":
		return uint16(pb.Type_TYPE_ACTION_DELETE_CONVERSATION), true
	case "mute_conversation":
		return uint16(pb.Type_TYPE_ACTION_MUTE_CONVERSATION), true
	case "unmute_conversation":
		return uint16(pb.Type_TYPE_ACTION_UNMUTE_CONVERSATION), true
	case "get_mutelist":
		return uint16(pb.Type_TYPE_ACTION_GET_MUTELIST), true
	case "sync_mutelist":
		return uint16(pb.Type_TYPE_ACTION_SYNC_MUTELIST), true
	case "create_group":
		return uint16(pb.Type_TYPE_ACTION_CREATE_GROUP), true
	case "get_group_infos":
		return uint16(pb.Type_TYPE_ACTION_GET_GROUP_INFOS), true
	case "get_group_members":
		return uint16(pb.Type_TYPE_ACTION_GET_GROUP_MEMBERS), true
	case "update_group_info":
		return uint16(pb.Type_TYPE_ACTION_UPDATE_GROUP_INFO), true
	case "add_group_member":
		return uint16(pb.Type_TYPE_ACTION_ADD_GROUP_MEMBER), true
	case "remove_group_member":
		return uint16(pb.Type_TYPE_ACTION_REMOVE_GROUP_MEMBER), true
	case "get_org_infos":
		return uint16(pb.Type_TYPE_ACTION_GET_ORG_INFOS), true
	case "get_org_tag_items":
		return uint16(pb.Type_TYPE_ACTION_GET_ORG_TAG_ITEMS), true
	case "sync_org_tags":
		return uint16(pb.Type_TYPE_ACTION_SYNC_ORG_TAGS), true
	default:
		return 0, false
	}
}

// NewRequestMessageByType 按 type 构造空请求消息。
func NewRequestMessageByType(typeID uint16) (proto.Message, bool) {
	switch pb.Type(typeID) {
	case pb.Type_TYPE_ACTION_REGISTER:
		return &pb.RegisterRequest{}, true
	case pb.Type_TYPE_ACTION_LOGIN:
		return &pb.LoginRequest{}, true
	case pb.Type_TYPE_ACTION_AUTHENTICATE:
		return &pb.AuthenticateRequest{}, true
	case pb.Type_TYPE_ACTION_LOGOUT:
		return &pb.LogoutRequest{}, true
	case pb.Type_TYPE_ACTION_PING:
		return &pb.PingRequest{}, true
	case pb.Type_TYPE_ACTION_UPDATE_USER_INFO:
		return &pb.UpdateUserInfoRequest{}, true
	case pb.Type_TYPE_ACTION_UPDATE_PASSWORD:
		return &pb.UpdatePasswordRequest{}, true
	case pb.Type_TYPE_ACTION_GET_USER_INFOS:
		return &pb.GetUserInfosRequest{}, true
	case pb.Type_TYPE_ACTION_SEARCH_USER:
		return &pb.SearchUserRequest{}, true
	case pb.Type_TYPE_ACTION_ADD_FRIEND:
		return &pb.AddFriendRequest{}, true
	case pb.Type_TYPE_ACTION_ACCEPT_FRIEND:
		return &pb.AcceptFriendRequest{}, true
	case pb.Type_TYPE_ACTION_REJECT_FRIEND:
		return &pb.RejectFriendRequest{}, true
	case pb.Type_TYPE_ACTION_DELETE_FRIEND:
		return &pb.DeleteFriendRequest{}, true
	case pb.Type_TYPE_ACTION_UPDATE_REMARK:
		return &pb.UpdateRemarkRequest{}, true
	case pb.Type_TYPE_ACTION_GET_CONTACTS:
		return &pb.GetContactsRequest{}, true
	case pb.Type_TYPE_ACTION_GET_CONTACT_COUNT:
		return &pb.GetContactCountRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_CONTACTS:
		return &pb.SyncContactsRequest{}, true
	case pb.Type_TYPE_ACTION_FAVORITE_GROUP:
		return &pb.FavoriteGroupRequest{}, true
	case pb.Type_TYPE_ACTION_UNFAVORITE_GROUP:
		return &pb.UnfavoriteGroupRequest{}, true
	case pb.Type_TYPE_ACTION_BLOCK_USER:
		return &pb.BlockUserRequest{}, true
	case pb.Type_TYPE_ACTION_UNBLOCK_USER:
		return &pb.UnblockUserRequest{}, true
	case pb.Type_TYPE_ACTION_GET_BLOCKLIST:
		return &pb.GetBlocklistRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_BLOCKLIST:
		return &pb.SyncBlocklistRequest{}, true
	case pb.Type_TYPE_ACTION_SEND_MESSAGE:
		return &pb.SendMessageRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_MESSAGES:
		return &pb.SyncMessagesRequest{}, true
	case pb.Type_TYPE_ACTION_GET_MESSAGES:
		return &pb.GetMessagesRequest{}, true
	case pb.Type_TYPE_ACTION_DELETE_MESSAGE:
		return &pb.DeleteMessageRequest{}, true
	case pb.Type_TYPE_ACTION_GET_CONVERSATIONS:
		return &pb.GetConversationsRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_CONVERSATIONS:
		return &pb.SyncConversationsRequest{}, true
	case pb.Type_TYPE_ACTION_GET_UNREAD_COUNT:
		return &pb.GetUnreadCountRequest{}, true
	case pb.Type_TYPE_ACTION_CLEAR_UNREAD:
		return &pb.ClearUnreadRequest{}, true
	case pb.Type_TYPE_ACTION_DELETE_CONVERSATION:
		return &pb.DeleteConversationRequest{}, true
	case pb.Type_TYPE_ACTION_MUTE_CONVERSATION:
		return &pb.MuteConversationRequest{}, true
	case pb.Type_TYPE_ACTION_UNMUTE_CONVERSATION:
		return &pb.UnmuteConversationRequest{}, true
	case pb.Type_TYPE_ACTION_GET_MUTELIST:
		return &pb.GetMutelistRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_MUTELIST:
		return &pb.SyncMutelistRequest{}, true
	case pb.Type_TYPE_ACTION_CREATE_GROUP:
		return &pb.CreateGroupRequest{}, true
	case pb.Type_TYPE_ACTION_GET_GROUP_INFOS:
		return &pb.GetGroupInfosRequest{}, true
	case pb.Type_TYPE_ACTION_GET_GROUP_MEMBERS:
		return &pb.GetGroupMembersRequest{}, true
	case pb.Type_TYPE_ACTION_UPDATE_GROUP_INFO:
		return &pb.UpdateGroupInfoRequest{}, true
	case pb.Type_TYPE_ACTION_ADD_GROUP_MEMBER:
		return &pb.AddGroupMemberRequest{}, true
	case pb.Type_TYPE_ACTION_REMOVE_GROUP_MEMBER:
		return &pb.RemoveGroupMemberRequest{}, true
	case pb.Type_TYPE_ACTION_GET_ORG_INFOS:
		return &pb.GetOrgInfosRequest{}, true
	case pb.Type_TYPE_ACTION_GET_ORG_TAG_ITEMS:
		return &pb.GetOrgTagItemsRequest{}, true
	case pb.Type_TYPE_ACTION_SYNC_ORG_TAGS:
		return &pb.SyncOrgTagsRequest{}, true
	default:
		return nil, false
	}
}

// NewResponseMessageByType 按 type 构造空响应消息。
func NewResponseMessageByType(typeID uint16) (proto.Message, bool) {
	switch pb.Type(typeID) {
	case pb.Type_TYPE_ACTION_REGISTER:
		return &pb.RegisterResponse{}, true
	case pb.Type_TYPE_ACTION_LOGIN:
		return &pb.LoginResponse{}, true
	case pb.Type_TYPE_ACTION_AUTHENTICATE:
		return &pb.AuthenticateResponse{}, true
	case pb.Type_TYPE_ACTION_LOGOUT:
		return &pb.LogoutResponse{}, true
	case pb.Type_TYPE_ACTION_PING:
		return &pb.PingResponse{}, true
	case pb.Type_TYPE_ACTION_UPDATE_USER_INFO:
		return &pb.UpdateUserInfoResponse{}, true
	case pb.Type_TYPE_ACTION_UPDATE_PASSWORD:
		return &pb.UpdatePasswordResponse{}, true
	case pb.Type_TYPE_ACTION_GET_USER_INFOS:
		return &pb.GetUserInfosResponse{}, true
	case pb.Type_TYPE_ACTION_SEARCH_USER:
		return &pb.SearchUserResponse{}, true
	case pb.Type_TYPE_ACTION_ADD_FRIEND:
		return &pb.AddFriendResponse{}, true
	case pb.Type_TYPE_ACTION_ACCEPT_FRIEND:
		return &pb.AcceptFriendResponse{}, true
	case pb.Type_TYPE_ACTION_REJECT_FRIEND:
		return &pb.RejectFriendResponse{}, true
	case pb.Type_TYPE_ACTION_DELETE_FRIEND:
		return &pb.DeleteFriendResponse{}, true
	case pb.Type_TYPE_ACTION_UPDATE_REMARK:
		return &pb.UpdateRemarkResponse{}, true
	case pb.Type_TYPE_ACTION_GET_CONTACTS:
		return &pb.GetContactsResponse{}, true
	case pb.Type_TYPE_ACTION_GET_CONTACT_COUNT:
		return &pb.GetContactCountResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_CONTACTS:
		return &pb.SyncContactsResponse{}, true
	case pb.Type_TYPE_ACTION_FAVORITE_GROUP:
		return &pb.FavoriteGroupResponse{}, true
	case pb.Type_TYPE_ACTION_UNFAVORITE_GROUP:
		return &pb.UnfavoriteGroupResponse{}, true
	case pb.Type_TYPE_ACTION_BLOCK_USER:
		return &pb.BlockUserResponse{}, true
	case pb.Type_TYPE_ACTION_UNBLOCK_USER:
		return &pb.UnblockUserResponse{}, true
	case pb.Type_TYPE_ACTION_GET_BLOCKLIST:
		return &pb.GetBlocklistResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_BLOCKLIST:
		return &pb.SyncBlocklistResponse{}, true
	case pb.Type_TYPE_ACTION_SEND_MESSAGE:
		return &pb.SendMessageResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_MESSAGES:
		return &pb.SyncMessagesResponse{}, true
	case pb.Type_TYPE_ACTION_GET_MESSAGES:
		return &pb.GetMessagesResponse{}, true
	case pb.Type_TYPE_ACTION_DELETE_MESSAGE:
		return &pb.DeleteMessageResponse{}, true
	case pb.Type_TYPE_ACTION_GET_CONVERSATIONS:
		return &pb.GetConversationsResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_CONVERSATIONS:
		return &pb.SyncConversationsResponse{}, true
	case pb.Type_TYPE_ACTION_GET_UNREAD_COUNT:
		return &pb.GetUnreadCountResponse{}, true
	case pb.Type_TYPE_ACTION_CLEAR_UNREAD:
		return &pb.ClearUnreadResponse{}, true
	case pb.Type_TYPE_ACTION_DELETE_CONVERSATION:
		return &pb.DeleteConversationResponse{}, true
	case pb.Type_TYPE_ACTION_MUTE_CONVERSATION:
		return &pb.MuteConversationResponse{}, true
	case pb.Type_TYPE_ACTION_UNMUTE_CONVERSATION:
		return &pb.UnmuteConversationResponse{}, true
	case pb.Type_TYPE_ACTION_GET_MUTELIST:
		return &pb.GetMutelistResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_MUTELIST:
		return &pb.SyncMutelistResponse{}, true
	case pb.Type_TYPE_ACTION_CREATE_GROUP:
		return &pb.CreateGroupResponse{}, true
	case pb.Type_TYPE_ACTION_GET_GROUP_INFOS:
		return &pb.GetGroupInfosResponse{}, true
	case pb.Type_TYPE_ACTION_GET_GROUP_MEMBERS:
		return &pb.GetGroupMembersResponse{}, true
	case pb.Type_TYPE_ACTION_UPDATE_GROUP_INFO:
		return &pb.UpdateGroupInfoResponse{}, true
	case pb.Type_TYPE_ACTION_ADD_GROUP_MEMBER:
		return &pb.AddGroupMemberResponse{}, true
	case pb.Type_TYPE_ACTION_REMOVE_GROUP_MEMBER:
		return &pb.RemoveGroupMemberResponse{}, true
	case pb.Type_TYPE_ACTION_GET_ORG_INFOS:
		return &pb.GetOrgInfosResponse{}, true
	case pb.Type_TYPE_ACTION_GET_ORG_TAG_ITEMS:
		return &pb.GetOrgTagItemsResponse{}, true
	case pb.Type_TYPE_ACTION_SYNC_ORG_TAGS:
		return &pb.SyncOrgTagsResponse{}, true
	default:
		return nil, false
	}
}

// DispatchFrameResult 是一次 action frame 分发的结果。
type DispatchFrameResult struct {
	Type          pb.Type       // 请求 type
	Request       proto.Message // 解码后的请求，未知 type 时为 nil
	Response      proto.Message // 业务或错误响应
	ResponseFrame []byte        // 已编码、可直接写回的响应 frame
}

// DispatchActionFrame 完成 type -> request decode -> service method -> response encode -> response frame。
// 它不处理任何业务副作用（fanout 异步任务队列、通知、DB 写入都在 service 内部完成），
// 也不直接操作 WebSocket 连接状态；连接态绑定 / 清理由外层 HandleWS 基于结果处理。
func DispatchActionFrame(svc ActionService, info *service.BaseInfo, frame Frame) (*DispatchFrameResult, error) {
	if frame.RequestID == NotificationRequestID {
		return nil, fmt.Errorf("request_id=0 notification frame is not a valid action frame")
	}
	typeID := pb.Type(frame.Type)
	req, ok := NewRequestMessageByType(frame.Type)
	if !ok {
		return encodeDispatchResult(frame, typeID, nil,
			errorResponseByType(frame.Type, appmsg.ErrorCodeUnknownAction, fmt.Sprintf("unknown type: %d", frame.Type)))
	}
	if err := proto.Unmarshal(frame.Body, req); err != nil {
		return encodeDispatchResult(frame, typeID, req,
			errorResponseByType(frame.Type, appmsg.ErrorCodeInvalidProtobuf, err.Error()))
	}
	var resp proto.Message
	switch typeID {
	case pb.Type_TYPE_ACTION_REGISTER:
		resp = svc.Register(info, req.(*pb.RegisterRequest))
	case pb.Type_TYPE_ACTION_LOGIN:
		resp = svc.Login(info, req.(*pb.LoginRequest))
	case pb.Type_TYPE_ACTION_AUTHENTICATE:
		resp = svc.Authenticate(info, req.(*pb.AuthenticateRequest))
	case pb.Type_TYPE_ACTION_LOGOUT:
		resp = svc.Logout(info, req.(*pb.LogoutRequest))
	case pb.Type_TYPE_ACTION_PING:
		resp = svc.Ping(info, req.(*pb.PingRequest))
	case pb.Type_TYPE_ACTION_UPDATE_USER_INFO:
		resp = svc.UpdateUserInfo(info, req.(*pb.UpdateUserInfoRequest))
	case pb.Type_TYPE_ACTION_UPDATE_PASSWORD:
		resp = svc.UpdatePassword(info, req.(*pb.UpdatePasswordRequest))
	case pb.Type_TYPE_ACTION_GET_USER_INFOS:
		resp = svc.GetUserInfos(info, req.(*pb.GetUserInfosRequest))
	case pb.Type_TYPE_ACTION_SEARCH_USER:
		resp = svc.SearchUser(info, req.(*pb.SearchUserRequest))
	case pb.Type_TYPE_ACTION_ADD_FRIEND:
		resp = svc.AddFriend(info, req.(*pb.AddFriendRequest))
	case pb.Type_TYPE_ACTION_ACCEPT_FRIEND:
		resp = svc.AcceptFriend(info, req.(*pb.AcceptFriendRequest))
	case pb.Type_TYPE_ACTION_REJECT_FRIEND:
		resp = svc.RejectFriend(info, req.(*pb.RejectFriendRequest))
	case pb.Type_TYPE_ACTION_DELETE_FRIEND:
		resp = svc.DeleteFriend(info, req.(*pb.DeleteFriendRequest))
	case pb.Type_TYPE_ACTION_UPDATE_REMARK:
		resp = svc.UpdateRemark(info, req.(*pb.UpdateRemarkRequest))
	case pb.Type_TYPE_ACTION_GET_CONTACTS:
		resp = svc.GetContacts(info, req.(*pb.GetContactsRequest))
	case pb.Type_TYPE_ACTION_GET_CONTACT_COUNT:
		resp = svc.GetContactCount(info, req.(*pb.GetContactCountRequest))
	case pb.Type_TYPE_ACTION_SYNC_CONTACTS:
		resp = svc.SyncContacts(info, req.(*pb.SyncContactsRequest))
	case pb.Type_TYPE_ACTION_FAVORITE_GROUP:
		resp = svc.FavoriteGroup(info, req.(*pb.FavoriteGroupRequest))
	case pb.Type_TYPE_ACTION_UNFAVORITE_GROUP:
		resp = svc.UnfavoriteGroup(info, req.(*pb.UnfavoriteGroupRequest))
	case pb.Type_TYPE_ACTION_BLOCK_USER:
		resp = svc.BlockUser(info, req.(*pb.BlockUserRequest))
	case pb.Type_TYPE_ACTION_UNBLOCK_USER:
		resp = svc.UnblockUser(info, req.(*pb.UnblockUserRequest))
	case pb.Type_TYPE_ACTION_GET_BLOCKLIST:
		resp = svc.GetBlocklist(info, req.(*pb.GetBlocklistRequest))
	case pb.Type_TYPE_ACTION_SYNC_BLOCKLIST:
		resp = svc.SyncBlocklist(info, req.(*pb.SyncBlocklistRequest))
	case pb.Type_TYPE_ACTION_SEND_MESSAGE:
		resp = svc.SendMessage(info, req.(*pb.SendMessageRequest))
	case pb.Type_TYPE_ACTION_SYNC_MESSAGES:
		resp = svc.SyncMessages(info, req.(*pb.SyncMessagesRequest))
	case pb.Type_TYPE_ACTION_GET_MESSAGES:
		resp = svc.GetMessages(info, req.(*pb.GetMessagesRequest))
	case pb.Type_TYPE_ACTION_DELETE_MESSAGE:
		resp = svc.DeleteMessage(info, req.(*pb.DeleteMessageRequest))
	case pb.Type_TYPE_ACTION_GET_CONVERSATIONS:
		resp = svc.GetConversations(info, req.(*pb.GetConversationsRequest))
	case pb.Type_TYPE_ACTION_SYNC_CONVERSATIONS:
		resp = svc.SyncConversations(info, req.(*pb.SyncConversationsRequest))
	case pb.Type_TYPE_ACTION_GET_UNREAD_COUNT:
		resp = svc.GetUnreadCount(info, req.(*pb.GetUnreadCountRequest))
	case pb.Type_TYPE_ACTION_CLEAR_UNREAD:
		resp = svc.ClearUnread(info, req.(*pb.ClearUnreadRequest))
	case pb.Type_TYPE_ACTION_DELETE_CONVERSATION:
		resp = svc.DeleteConversation(info, req.(*pb.DeleteConversationRequest))
	case pb.Type_TYPE_ACTION_MUTE_CONVERSATION:
		resp = svc.MuteConversation(info, req.(*pb.MuteConversationRequest))
	case pb.Type_TYPE_ACTION_UNMUTE_CONVERSATION:
		resp = svc.UnmuteConversation(info, req.(*pb.UnmuteConversationRequest))
	case pb.Type_TYPE_ACTION_GET_MUTELIST:
		resp = svc.GetMutelist(info, req.(*pb.GetMutelistRequest))
	case pb.Type_TYPE_ACTION_SYNC_MUTELIST:
		resp = svc.SyncMutelist(info, req.(*pb.SyncMutelistRequest))
	case pb.Type_TYPE_ACTION_CREATE_GROUP:
		resp = svc.CreateGroup(info, req.(*pb.CreateGroupRequest))
	case pb.Type_TYPE_ACTION_GET_GROUP_INFOS:
		resp = svc.GetGroupInfos(info, req.(*pb.GetGroupInfosRequest))
	case pb.Type_TYPE_ACTION_GET_GROUP_MEMBERS:
		resp = svc.GetGroupMembers(info, req.(*pb.GetGroupMembersRequest))
	case pb.Type_TYPE_ACTION_UPDATE_GROUP_INFO:
		resp = svc.UpdateGroupInfo(info, req.(*pb.UpdateGroupInfoRequest))
	case pb.Type_TYPE_ACTION_ADD_GROUP_MEMBER:
		resp = svc.AddGroupMember(info, req.(*pb.AddGroupMemberRequest))
	case pb.Type_TYPE_ACTION_REMOVE_GROUP_MEMBER:
		resp = svc.RemoveGroupMember(info, req.(*pb.RemoveGroupMemberRequest))
	case pb.Type_TYPE_ACTION_GET_ORG_INFOS:
		resp = svc.GetOrgInfos(info, req.(*pb.GetOrgInfosRequest))
	case pb.Type_TYPE_ACTION_GET_ORG_TAG_ITEMS:
		resp = svc.GetOrgTagItems(info, req.(*pb.GetOrgTagItemsRequest))
	case pb.Type_TYPE_ACTION_SYNC_ORG_TAGS:
		resp = svc.SyncOrgTags(info, req.(*pb.SyncOrgTagsRequest))
	default:
		resp = errorResponseByType(frame.Type, appmsg.ErrorCodeUnknownAction, fmt.Sprintf("unknown type: %d", frame.Type))
	}
	return encodeDispatchResult(frame, typeID, req, resp)
}

// encodeDispatchResult 用原 frame 的 codec / endian / request_id / type 编码响应 frame；
// 响应过大时改用 ERROR_FRAME_TOO_LARGE 错误响应。
func encodeDispatchResult(frame Frame, typeID pb.Type, req, resp proto.Message) (*DispatchFrameResult, error) {
	body, err := EncodeProtoBody(frame.Codec, resp)
	if err != nil {
		return nil, err
	}
	data, err := EncodeFrameWithEndian(frame.Codec, frame.Endian, frame.RequestID, frame.Type, body)
	if err != nil {
		resp = errorResponseByType(frame.Type, appmsg.ErrorCodeFrameTooLarge, "frame packet too large")
		body, err = EncodeProtoBody(frame.Codec, resp)
		if err != nil {
			return nil, err
		}
		data, err = EncodeFrameWithEndian(frame.Codec, frame.Endian, frame.RequestID, frame.Type, body)
		if err != nil {
			return nil, err
		}
	}
	return &DispatchFrameResult{Type: typeID, Request: req, Response: resp, ResponseFrame: data}, nil
}
