// Code generated by protocolgen; DO NOT EDIT.

package ws

import (
	"yimsg/internal/protocol/pb"
	"yimsg/internal/service"
)

// ActionService 是服务端 action 入方向接口，由 *service.AppState 实现。
// 新增 TYPE_ACTION_* 后必须在 service 层实现对应方法，否则下方断言导致编译失败。
type ActionService interface {
	Register(info *service.BaseInfo, req *pb.RegisterRequest) *pb.RegisterResponse
	Login(info *service.BaseInfo, req *pb.LoginRequest) *pb.LoginResponse
	Authenticate(info *service.BaseInfo, req *pb.AuthenticateRequest) *pb.AuthenticateResponse
	Logout(info *service.BaseInfo, req *pb.LogoutRequest) *pb.LogoutResponse
	Ping(info *service.BaseInfo, req *pb.PingRequest) *pb.PingResponse
	UpdateUserInfo(info *service.BaseInfo, req *pb.UpdateUserInfoRequest) *pb.UpdateUserInfoResponse
	UpdatePassword(info *service.BaseInfo, req *pb.UpdatePasswordRequest) *pb.UpdatePasswordResponse
	GetUserInfos(info *service.BaseInfo, req *pb.GetUserInfosRequest) *pb.GetUserInfosResponse
	SearchUser(info *service.BaseInfo, req *pb.SearchUserRequest) *pb.SearchUserResponse
	AddFriend(info *service.BaseInfo, req *pb.AddFriendRequest) *pb.AddFriendResponse
	AcceptFriend(info *service.BaseInfo, req *pb.AcceptFriendRequest) *pb.AcceptFriendResponse
	RejectFriend(info *service.BaseInfo, req *pb.RejectFriendRequest) *pb.RejectFriendResponse
	DeleteFriend(info *service.BaseInfo, req *pb.DeleteFriendRequest) *pb.DeleteFriendResponse
	UpdateRemark(info *service.BaseInfo, req *pb.UpdateRemarkRequest) *pb.UpdateRemarkResponse
	GetContacts(info *service.BaseInfo, req *pb.GetContactsRequest) *pb.GetContactsResponse
	GetContactCount(info *service.BaseInfo, req *pb.GetContactCountRequest) *pb.GetContactCountResponse
	SyncContacts(info *service.BaseInfo, req *pb.SyncContactsRequest) *pb.SyncContactsResponse
	FavoriteGroup(info *service.BaseInfo, req *pb.FavoriteGroupRequest) *pb.FavoriteGroupResponse
	UnfavoriteGroup(info *service.BaseInfo, req *pb.UnfavoriteGroupRequest) *pb.UnfavoriteGroupResponse
	BlockUser(info *service.BaseInfo, req *pb.BlockUserRequest) *pb.BlockUserResponse
	UnblockUser(info *service.BaseInfo, req *pb.UnblockUserRequest) *pb.UnblockUserResponse
	GetBlocklist(info *service.BaseInfo, req *pb.GetBlocklistRequest) *pb.GetBlocklistResponse
	SyncBlocklist(info *service.BaseInfo, req *pb.SyncBlocklistRequest) *pb.SyncBlocklistResponse
	SendMessage(info *service.BaseInfo, req *pb.SendMessageRequest) *pb.SendMessageResponse
	SyncMessages(info *service.BaseInfo, req *pb.SyncMessagesRequest) *pb.SyncMessagesResponse
	GetMessages(info *service.BaseInfo, req *pb.GetMessagesRequest) *pb.GetMessagesResponse
	DeleteMessage(info *service.BaseInfo, req *pb.DeleteMessageRequest) *pb.DeleteMessageResponse
	GetConversations(info *service.BaseInfo, req *pb.GetConversationsRequest) *pb.GetConversationsResponse
	SyncConversations(info *service.BaseInfo, req *pb.SyncConversationsRequest) *pb.SyncConversationsResponse
	GetUnreadCount(info *service.BaseInfo, req *pb.GetUnreadCountRequest) *pb.GetUnreadCountResponse
	ClearUnread(info *service.BaseInfo, req *pb.ClearUnreadRequest) *pb.ClearUnreadResponse
	DeleteConversation(info *service.BaseInfo, req *pb.DeleteConversationRequest) *pb.DeleteConversationResponse
	MuteConversation(info *service.BaseInfo, req *pb.MuteConversationRequest) *pb.MuteConversationResponse
	UnmuteConversation(info *service.BaseInfo, req *pb.UnmuteConversationRequest) *pb.UnmuteConversationResponse
	GetMutelist(info *service.BaseInfo, req *pb.GetMutelistRequest) *pb.GetMutelistResponse
	SyncMutelist(info *service.BaseInfo, req *pb.SyncMutelistRequest) *pb.SyncMutelistResponse
	CreateGroup(info *service.BaseInfo, req *pb.CreateGroupRequest) *pb.CreateGroupResponse
	GetGroupInfos(info *service.BaseInfo, req *pb.GetGroupInfosRequest) *pb.GetGroupInfosResponse
	GetGroupMembers(info *service.BaseInfo, req *pb.GetGroupMembersRequest) *pb.GetGroupMembersResponse
	UpdateGroupInfo(info *service.BaseInfo, req *pb.UpdateGroupInfoRequest) *pb.UpdateGroupInfoResponse
	AddGroupMember(info *service.BaseInfo, req *pb.AddGroupMemberRequest) *pb.AddGroupMemberResponse
	RemoveGroupMember(info *service.BaseInfo, req *pb.RemoveGroupMemberRequest) *pb.RemoveGroupMemberResponse
	GetOrgInfos(info *service.BaseInfo, req *pb.GetOrgInfosRequest) *pb.GetOrgInfosResponse
	GetTags(info *service.BaseInfo, req *pb.GetTagsRequest) *pb.GetTagsResponse
	SyncTags(info *service.BaseInfo, req *pb.SyncTagsRequest) *pb.SyncTagsResponse
	GetTagInfos(info *service.BaseInfo, req *pb.GetTagInfosRequest) *pb.GetTagInfosResponse
	CreateOrgTag(info *service.BaseInfo, req *pb.CreateOrgTagRequest) *pb.CreateOrgTagResponse
	RenameOrgTag(info *service.BaseInfo, req *pb.RenameOrgTagRequest) *pb.RenameOrgTagResponse
	DeleteOrgTag(info *service.BaseInfo, req *pb.DeleteOrgTagRequest) *pb.DeleteOrgTagResponse
	LinkOrgTag(info *service.BaseInfo, req *pb.LinkOrgTagRequest) *pb.LinkOrgTagResponse
	AddOrgMember(info *service.BaseInfo, req *pb.AddOrgMemberRequest) *pb.AddOrgMemberResponse
	RemoveOrgMember(info *service.BaseInfo, req *pb.RemoveOrgMemberRequest) *pb.RemoveOrgMemberResponse
	SetOrgItemRank(info *service.BaseInfo, req *pb.SetOrgItemRankRequest) *pb.SetOrgItemRankResponse
	RenameOrg(info *service.BaseInfo, req *pb.RenameOrgRequest) *pb.RenameOrgResponse
	GrantOrgAdmin(info *service.BaseInfo, req *pb.GrantOrgAdminRequest) *pb.GrantOrgAdminResponse
	RevokeOrgAdmin(info *service.BaseInfo, req *pb.RevokeOrgAdminRequest) *pb.RevokeOrgAdminResponse
	ListOrgAdmins(info *service.BaseInfo, req *pb.ListOrgAdminsRequest) *pb.ListOrgAdminsResponse
}

// 编译期断言：AppState 必须实现全部 action。
var _ ActionService = (*service.AppState)(nil)
