// Code generated by protocolgen; DO NOT EDIT.

package ws

import (
	"fmt"

	"yimsg/internal/protocol/pb"

	"google.golang.org/protobuf/proto"
)

// NewMessagesReceivedNotificationFrame 编码 messages:received 通知 frame（request_id=0）。
func NewMessagesReceivedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.MessagesReceivedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_MESSAGES_RECEIVED), n)
}

// NewContactsUpdatedNotificationFrame 编码 contacts:updated 通知 frame（request_id=0）。
func NewContactsUpdatedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.ContactsUpdatedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_CONTACTS_UPDATED), n)
}

// NewSessionKickedNotificationFrame 编码 session:kicked 通知 frame（request_id=0）。
func NewSessionKickedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.SessionKickedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_SESSION_KICKED), n)
}

// NewBlocklistUpdatedNotificationFrame 编码 blocklist:updated 通知 frame（request_id=0）。
func NewBlocklistUpdatedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.BlocklistUpdatedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_BLOCKLIST_UPDATED), n)
}

// NewMutelistUpdatedNotificationFrame 编码 mutelist:updated 通知 frame（request_id=0）。
func NewMutelistUpdatedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.MutelistUpdatedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_MUTELIST_UPDATED), n)
}

// NewConversationsClearunreadNotificationFrame 编码 conversations:clearunread 通知 frame（request_id=0）。
func NewConversationsClearunreadNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.ConversationsClearunreadNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_CONVERSATIONS_CLEARUNREAD), n)
}

// NewConversationsDeleteNotificationFrame 编码 conversations:delete 通知 frame（request_id=0）。
func NewConversationsDeleteNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.ConversationsDeleteNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_CONVERSATIONS_DELETE), n)
}

// NewMessagesDeleteNotificationFrame 编码 messages:delete 通知 frame（request_id=0）。
func NewMessagesDeleteNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.MessagesDeleteNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_MESSAGES_DELETE), n)
}

// NewOrgUpdatedNotificationFrame 编码 org:updated 通知 frame（request_id=0）。
func NewOrgUpdatedNotificationFrame(codec FrameCodec, endian FrameEndian, n *pb.OrgUpdatedNotification) ([]byte, error) {
	return encodeNotificationFrame(codec, endian, uint16(pb.Type_TYPE_NOTIFY_ORG_UPDATED), n)
}

// EncodeNotificationFrame 按 notification 消息类型选择对应 helper 编码 frame。
func EncodeNotificationFrame(codec FrameCodec, endian FrameEndian, n proto.Message) ([]byte, error) {
	switch v := n.(type) {
	case *pb.MessagesReceivedNotification:
		return NewMessagesReceivedNotificationFrame(codec, endian, v)
	case *pb.ContactsUpdatedNotification:
		return NewContactsUpdatedNotificationFrame(codec, endian, v)
	case *pb.SessionKickedNotification:
		return NewSessionKickedNotificationFrame(codec, endian, v)
	case *pb.BlocklistUpdatedNotification:
		return NewBlocklistUpdatedNotificationFrame(codec, endian, v)
	case *pb.MutelistUpdatedNotification:
		return NewMutelistUpdatedNotificationFrame(codec, endian, v)
	case *pb.ConversationsClearunreadNotification:
		return NewConversationsClearunreadNotificationFrame(codec, endian, v)
	case *pb.ConversationsDeleteNotification:
		return NewConversationsDeleteNotificationFrame(codec, endian, v)
	case *pb.MessagesDeleteNotification:
		return NewMessagesDeleteNotificationFrame(codec, endian, v)
	case *pb.OrgUpdatedNotification:
		return NewOrgUpdatedNotificationFrame(codec, endian, v)
	default:
		return nil, fmt.Errorf("unknown notification message: %T", n)
	}
}

// encodeNotificationFrame 固定 request_id=0，对通知消息编码 body 后拼装 frame。
func encodeNotificationFrame(codec FrameCodec, endian FrameEndian, typeID uint16, n proto.Message) ([]byte, error) {
	body, err := EncodeProtoBody(codec, n)
	if err != nil {
		return nil, err
	}
	return EncodeFrameWithEndian(codec, endian, NotificationRequestID, typeID, body)
}

// NewNotificationMessageByType 按 type 构造空通知消息，用于解码。
func NewNotificationMessageByType(typeID uint16) (proto.Message, bool) {
	switch pb.Type(typeID) {
	case pb.Type_TYPE_NOTIFY_MESSAGES_RECEIVED:
		return &pb.MessagesReceivedNotification{}, true
	case pb.Type_TYPE_NOTIFY_CONTACTS_UPDATED:
		return &pb.ContactsUpdatedNotification{}, true
	case pb.Type_TYPE_NOTIFY_SESSION_KICKED:
		return &pb.SessionKickedNotification{}, true
	case pb.Type_TYPE_NOTIFY_BLOCKLIST_UPDATED:
		return &pb.BlocklistUpdatedNotification{}, true
	case pb.Type_TYPE_NOTIFY_MUTELIST_UPDATED:
		return &pb.MutelistUpdatedNotification{}, true
	case pb.Type_TYPE_NOTIFY_CONVERSATIONS_CLEARUNREAD:
		return &pb.ConversationsClearunreadNotification{}, true
	case pb.Type_TYPE_NOTIFY_CONVERSATIONS_DELETE:
		return &pb.ConversationsDeleteNotification{}, true
	case pb.Type_TYPE_NOTIFY_MESSAGES_DELETE:
		return &pb.MessagesDeleteNotification{}, true
	case pb.Type_TYPE_NOTIFY_ORG_UPDATED:
		return &pb.OrgUpdatedNotification{}, true
	default:
		return nil, false
	}
}

// notificationTypeOf 把通知消息映射为 type id。
func notificationTypeOf(n proto.Message) (uint16, bool) {
	switch n.(type) {
	case *pb.MessagesReceivedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_MESSAGES_RECEIVED), true
	case *pb.ContactsUpdatedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_CONTACTS_UPDATED), true
	case *pb.SessionKickedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_SESSION_KICKED), true
	case *pb.BlocklistUpdatedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_BLOCKLIST_UPDATED), true
	case *pb.MutelistUpdatedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_MUTELIST_UPDATED), true
	case *pb.ConversationsClearunreadNotification:
		return uint16(pb.Type_TYPE_NOTIFY_CONVERSATIONS_CLEARUNREAD), true
	case *pb.ConversationsDeleteNotification:
		return uint16(pb.Type_TYPE_NOTIFY_CONVERSATIONS_DELETE), true
	case *pb.MessagesDeleteNotification:
		return uint16(pb.Type_TYPE_NOTIFY_MESSAGES_DELETE), true
	case *pb.OrgUpdatedNotification:
		return uint16(pb.Type_TYPE_NOTIFY_ORG_UPDATED), true
	default:
		return 0, false
	}
}
