// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: taskpayload.proto

// taskpayload.proto 定义异步任务队列（server/internal/taskqueue）fanout 任务的持久化
// 载荷。这是服务端内部实现细节，不是 protocol/yimsg.proto 定义的
// 客户端-服务端协议，因此单独成组；tools/cmd/protocolgen 仅统一调用 protoc 和补 SPDX，
// 不把它纳入公开协议 manifest。
//
// 重新生成：在仓库根目录运行
//   go run ./tools/cmd/protocolgen

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupMessageTask 是一条群消息（普通或撤回）向其余成员 fanout 的任务载荷。
// Recalled 为 true 时携带撤回相关字段：把原消息覆盖为撤回占位，并写入一条撤回事件消息。
type GroupMessageTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MsgId            string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromUid          int64                  `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	GroupId          int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Recalled         bool                   `protobuf:"varint,4,opt,name=recalled,proto3" json:"recalled,omitempty"`
	MsgType          int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Body             []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	SearchText       string                 `protobuf:"bytes,7,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	SendTime         int64                  `protobuf:"varint,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	TargetUids       []int64                `protobuf:"varint,9,rep,packed,name=target_uids,json=targetUids,proto3" json:"target_uids,omitempty"`
	RecallMsgId      string                 `protobuf:"bytes,10,opt,name=recall_msg_id,json=recallMsgId,proto3" json:"recall_msg_id,omitempty"`
	RecallMsgType    int32                  `protobuf:"varint,11,opt,name=recall_msg_type,json=recallMsgType,proto3" json:"recall_msg_type,omitempty"`
	RecallBody       []byte                 `protobuf:"bytes,12,opt,name=recall_body,json=recallBody,proto3" json:"recall_body,omitempty"`
	RecallSearchText string                 `protobuf:"bytes,13,opt,name=recall_search_text,json=recallSearchText,proto3" json:"recall_search_text,omitempty"`
	RecallTime       int64                  `protobuf:"varint,14,opt,name=recall_time,json=recallTime,proto3" json:"recall_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupMessageTask) Reset() {
	*x = GroupMessageTask{}
	mi := &file_taskpayload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessageTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageTask) ProtoMessage() {}

func (x *GroupMessageTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskpayload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageTask.ProtoReflect.Descriptor instead.
func (*GroupMessageTask) Descriptor() ([]byte, []int) {
	return file_taskpayload_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMessageTask) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *GroupMessageTask) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *GroupMessageTask) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMessageTask) GetRecalled() bool {
	if x != nil {
		return x.Recalled
	}
	return false
}

func (x *GroupMessageTask) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *GroupMessageTask) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GroupMessageTask) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *GroupMessageTask) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *GroupMessageTask) GetTargetUids() []int64 {
	if x != nil {
		return x.TargetUids
	}
	return nil
}

func (x *GroupMessageTask) GetRecallMsgId() string {
	if x != nil {
		return x.RecallMsgId
	}
	return ""
}

func (x *GroupMessageTask) GetRecallMsgType() int32 {
	if x != nil {
		return x.RecallMsgType
	}
	return 0
}

func (x *GroupMessageTask) GetRecallBody() []byte {
	if x != nil {
		return x.RecallBody
	}
	return nil
}

func (x *GroupMessageTask) GetRecallSearchText() string {
	if x != nil {
		return x.RecallSearchText
	}
	return ""
}

func (x *GroupMessageTask) GetRecallTime() int64 {
	if x != nil {
		return x.RecallTime
	}
	return 0
}

// GroupSystemTask 是一条群系统消息向全体成员 fanout 的任务载荷。
type GroupSystemTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	SearchText    string                 `protobuf:"bytes,4,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	SendTime      int64                  `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Uids          []int64                `protobuf:"varint,6,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSystemTask) Reset() {
	*x = GroupSystemTask{}
	mi := &file_taskpayload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSystemTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSystemTask) ProtoMessage() {}

func (x *GroupSystemTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskpayload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSystemTask.ProtoReflect.Descriptor instead.
func (*GroupSystemTask) Descriptor() ([]byte, []int) {
	return file_taskpayload_proto_rawDescGZIP(), []int{1}
}

func (x *GroupSystemTask) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *GroupSystemTask) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSystemTask) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GroupSystemTask) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *GroupSystemTask) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *GroupSystemTask) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// OrgUpdatedTask 是 org:updated 扇出任务载荷。
type OrgUpdatedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgUpdatedTask) Reset() {
	*x = OrgUpdatedTask{}
	mi := &file_taskpayload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgUpdatedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgUpdatedTask) ProtoMessage() {}

func (x *OrgUpdatedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskpayload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgUpdatedTask.ProtoReflect.Descriptor instead.
func (*OrgUpdatedTask) Descriptor() ([]byte, []int) {
	return file_taskpayload_proto_rawDescGZIP(), []int{2}
}

func (x *OrgUpdatedTask) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

// OrgDeletedTask 是组织删除后、成员通讯录组织行异步清理任务载荷。
// MemberUIDs 在组织结构物理删除前快照——事后组织分片已经查不到"谁曾是成员"。
type OrgDeletedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	MemberUids    []int64                `protobuf:"varint,2,rep,packed,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgDeletedTask) Reset() {
	*x = OrgDeletedTask{}
	mi := &file_taskpayload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgDeletedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgDeletedTask) ProtoMessage() {}

func (x *OrgDeletedTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskpayload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgDeletedTask.ProtoReflect.Descriptor instead.
func (*OrgDeletedTask) Descriptor() ([]byte, []int) {
	return file_taskpayload_proto_rawDescGZIP(), []int{3}
}

func (x *OrgDeletedTask) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *OrgDeletedTask) GetMemberUids() []int64 {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

var File_taskpayload_proto protoreflect.FileDescriptor

const file_taskpayload_proto_rawDesc = "" +
	"\n" +
	"\x11taskpayload.proto\x12\x12yimsg.service.task\"\xc5\x03\n" +
	"\x10GroupMessageTask\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x19\n" +
	"\bfrom_uid\x18\x02 \x01(\x03R\afromUid\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1a\n" +
	"\brecalled\x18\x04 \x01(\bR\brecalled\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\x1f\n" +
	"\vsearch_text\x18\a \x01(\tR\n" +
	"searchText\x12\x1b\n" +
	"\tsend_time\x18\b \x01(\x03R\bsendTime\x12\x1f\n" +
	"\vtarget_uids\x18\t \x03(\x03R\n" +
	"targetUids\x12\"\n" +
	"\rrecall_msg_id\x18\n" +
	" \x01(\tR\vrecallMsgId\x12&\n" +
	"\x0frecall_msg_type\x18\v \x01(\x05R\rrecallMsgType\x12\x1f\n" +
	"\vrecall_body\x18\f \x01(\fR\n" +
	"recallBody\x12,\n" +
	"\x12recall_search_text\x18\r \x01(\tR\x10recallSearchText\x12\x1f\n" +
	"\vrecall_time\x18\x0e \x01(\x03R\n" +
	"recallTime\"\xa9\x01\n" +
	"\x0fGroupSystemTask\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1f\n" +
	"\vsearch_text\x18\x04 \x01(\tR\n" +
	"searchText\x12\x1b\n" +
	"\tsend_time\x18\x05 \x01(\x03R\bsendTime\x12\x12\n" +
	"\x04uids\x18\x06 \x03(\x03R\x04uids\"'\n" +
	"\x0eOrgUpdatedTask\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\"H\n" +
	"\x0eOrgDeletedTask\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x1f\n" +
	"\vmember_uids\x18\x02 \x03(\x03R\n" +
	"memberUidsB-Z+yimsg/server/internal/service/taskpb;taskpbb\x06proto3"

var (
	file_taskpayload_proto_rawDescOnce sync.Once
	file_taskpayload_proto_rawDescData []byte
)

func file_taskpayload_proto_rawDescGZIP() []byte {
	file_taskpayload_proto_rawDescOnce.Do(func() {
		file_taskpayload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskpayload_proto_rawDesc), len(file_taskpayload_proto_rawDesc)))
	})
	return file_taskpayload_proto_rawDescData
}

var file_taskpayload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_taskpayload_proto_goTypes = []any{
	(*GroupMessageTask)(nil), // 0: yimsg.service.task.GroupMessageTask
	(*GroupSystemTask)(nil),  // 1: yimsg.service.task.GroupSystemTask
	(*OrgUpdatedTask)(nil),   // 2: yimsg.service.task.OrgUpdatedTask
	(*OrgDeletedTask)(nil),   // 3: yimsg.service.task.OrgDeletedTask
}
var file_taskpayload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taskpayload_proto_init() }
func file_taskpayload_proto_init() {
	if File_taskpayload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskpayload_proto_rawDesc), len(file_taskpayload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskpayload_proto_goTypes,
		DependencyIndexes: file_taskpayload_proto_depIdxs,
		MessageInfos:      file_taskpayload_proto_msgTypes,
	}.Build()
	File_taskpayload_proto = out.File
	file_taskpayload_proto_goTypes = nil
	file_taskpayload_proto_depIdxs = nil
}
