package protocolgen

import (
	"fmt"
	"go/format"
	"strings"
)

const goGeneratedHeader = "// Code generated by protocolgen; DO NOT EDIT.\n"

// GenGoActionService 生成 ActionService 接口与编译期断言。
func GenGoActionService(m *Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(goGeneratedHeader)
	b.WriteString("\npackage ws\n\n")
	b.WriteString("import (\n\t\"yimsg/internal/protocol/pb\"\n\t\"yimsg/internal/service\"\n)\n\n")
	b.WriteString("// ActionService 是服务端 action 入方向接口，由 *service.AppState 实现。\n")
	b.WriteString("// 新增 TYPE_ACTION_* 后必须在 service 层实现对应方法，否则下方断言导致编译失败。\n")
	b.WriteString("type ActionService interface {\n")
	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("\t%s(info *service.BaseInfo, req *pb.%s) *pb.%s\n", a.GoMethod, a.RequestMessage, a.ResponseMessage))
	}
	b.WriteString("}\n\n")
	b.WriteString("// 编译期断言：AppState 必须实现全部 action。\n")
	b.WriteString("var _ ActionService = (*service.AppState)(nil)\n")
	return format.Source([]byte(b.String()))
}

// GenGoDispatch 生成 type 工厂与 DispatchActionFrame。
func GenGoDispatch(m *Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(goGeneratedHeader)
	b.WriteString("\npackage ws\n\n")
	b.WriteString("import (\n\t\"fmt\"\n\n\t\"yimsg/internal/appmsg\"\n\t\"yimsg/internal/protocol/pb\"\n\t\"yimsg/internal/service\"\n\n\t\"google.golang.org/protobuf/proto\"\n)\n\n")

	// ActionType: action 名 -> type id。
	b.WriteString("// ActionType 把 action 名映射为 type id。\n")
	b.WriteString("func ActionType(action string) (uint16, bool) {\n\tswitch action {\n")
	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("\tcase %q:\n\t\treturn uint16(pb.Type_%s), true\n", a.ActionName, a.EnumName))
	}
	b.WriteString("\tdefault:\n\t\treturn 0, false\n\t}\n}\n\n")

	// NewRequestMessageByType。
	b.WriteString("// NewRequestMessageByType 按 type 构造空请求消息。\n")
	b.WriteString("func NewRequestMessageByType(typeID uint16) (proto.Message, bool) {\n\tswitch pb.Type(typeID) {\n")
	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("\tcase pb.Type_%s:\n\t\treturn &pb.%s{}, true\n", a.EnumName, a.RequestMessage))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n}\n\n")

	// NewResponseMessageByType。
	b.WriteString("// NewResponseMessageByType 按 type 构造空响应消息。\n")
	b.WriteString("func NewResponseMessageByType(typeID uint16) (proto.Message, bool) {\n\tswitch pb.Type(typeID) {\n")
	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("\tcase pb.Type_%s:\n\t\treturn &pb.%s{}, true\n", a.EnumName, a.ResponseMessage))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n}\n\n")

	// DispatchFrameResult + DispatchActionFrame。
	b.WriteString(`// DispatchFrameResult 是一次 action frame 分发的结果。
type DispatchFrameResult struct {
	Type          pb.Type       // 请求 type
	Request       proto.Message // 解码后的请求，未知 type 时为 nil
	Response      proto.Message // 业务或错误响应
	ResponseFrame []byte        // 已编码、可直接写回的响应 frame
}

// DispatchActionFrame 完成 type -> request decode -> service method -> response encode -> response frame。
// 它不处理任何业务副作用（fanout 异步任务队列、通知、DB 写入都在 service 内部完成），
// 也不直接操作 WebSocket 连接状态；连接态绑定 / 清理由外层 HandleWS 基于结果处理。
func DispatchActionFrame(svc ActionService, info *service.BaseInfo, frame Frame) (*DispatchFrameResult, error) {
	if frame.RequestID == NotificationRequestID {
		return nil, fmt.Errorf("request_id=0 notification frame is not a valid action frame")
	}
	typeID := pb.Type(frame.Type)
	req, ok := NewRequestMessageByType(frame.Type)
	if !ok {
		return encodeDispatchResult(frame, typeID, nil,
			errorResponseByType(frame.Type, appmsg.ErrorCodeUnknownAction, fmt.Sprintf("unknown type: %d", frame.Type)))
	}
	if err := proto.Unmarshal(frame.Body, req); err != nil {
		return encodeDispatchResult(frame, typeID, req,
			errorResponseByType(frame.Type, appmsg.ErrorCodeInvalidProtobuf, err.Error()))
	}
	var resp proto.Message
	switch typeID {
`)
	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("\tcase pb.Type_%s:\n\t\tresp = svc.%s(info, req.(*pb.%s))\n", a.EnumName, a.GoMethod, a.RequestMessage))
	}
	b.WriteString(`	default:
		resp = errorResponseByType(frame.Type, appmsg.ErrorCodeUnknownAction, fmt.Sprintf("unknown type: %d", frame.Type))
	}
	return encodeDispatchResult(frame, typeID, req, resp)
}

// encodeDispatchResult 用原 frame 的 codec / endian / request_id / type 编码响应 frame；
// 响应过大时改用 ERROR_FRAME_TOO_LARGE 错误响应。
func encodeDispatchResult(frame Frame, typeID pb.Type, req, resp proto.Message) (*DispatchFrameResult, error) {
	body, err := EncodeProtoBody(frame.Codec, resp)
	if err != nil {
		return nil, err
	}
	data, err := EncodeFrameWithEndian(frame.Codec, frame.Endian, frame.RequestID, frame.Type, body)
	if err != nil {
		resp = errorResponseByType(frame.Type, appmsg.ErrorCodeFrameTooLarge, "frame packet too large")
		body, err = EncodeProtoBody(frame.Codec, resp)
		if err != nil {
			return nil, err
		}
		data, err = EncodeFrameWithEndian(frame.Codec, frame.Endian, frame.RequestID, frame.Type, body)
		if err != nil {
			return nil, err
		}
	}
	return &DispatchFrameResult{Type: typeID, Request: req, Response: resp, ResponseFrame: data}, nil
}
`)
	return format.Source([]byte(b.String()))
}

// GenGoNotification 生成通知出方向 frame helper 与工厂。
func GenGoNotification(m *Manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString(goGeneratedHeader)
	b.WriteString("\npackage ws\n\n")
	b.WriteString("import (\n\t\"fmt\"\n\n\t\"yimsg/internal/protocol/pb\"\n\n\t\"google.golang.org/protobuf/proto\"\n)\n\n")

	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("// %s 编码 %s 通知 frame（request_id=0）。\n", n.GoHelper, n.Name))
		b.WriteString(fmt.Sprintf("func %s(codec FrameCodec, endian FrameEndian, n *pb.%s) ([]byte, error) {\n", n.GoHelper, n.MessageType))
		b.WriteString(fmt.Sprintf("\treturn encodeNotificationFrame(codec, endian, uint16(pb.Type_%s), n)\n}\n\n", n.EnumName))
	}

	b.WriteString("// EncodeNotificationFrame 按 notification 消息类型选择对应 helper 编码 frame。\n")
	b.WriteString("func EncodeNotificationFrame(codec FrameCodec, endian FrameEndian, n proto.Message) ([]byte, error) {\n\tswitch v := n.(type) {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("\tcase *pb.%s:\n\t\treturn %s(codec, endian, v)\n", n.MessageType, n.GoHelper))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown notification message: %T\", n)\n\t}\n}\n\n")

	b.WriteString(`// encodeNotificationFrame 固定 request_id=0，对通知消息编码 body 后拼装 frame。
func encodeNotificationFrame(codec FrameCodec, endian FrameEndian, typeID uint16, n proto.Message) ([]byte, error) {
	body, err := EncodeProtoBody(codec, n)
	if err != nil {
		return nil, err
	}
	return EncodeFrameWithEndian(codec, endian, NotificationRequestID, typeID, body)
}

`)

	b.WriteString("// NewNotificationMessageByType 按 type 构造空通知消息，用于解码。\n")
	b.WriteString("func NewNotificationMessageByType(typeID uint16) (proto.Message, bool) {\n\tswitch pb.Type(typeID) {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("\tcase pb.Type_%s:\n\t\treturn &pb.%s{}, true\n", n.EnumName, n.MessageType))
	}
	b.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n}\n\n")

	b.WriteString("// notificationTypeOf 把通知消息映射为 type id。\n")
	b.WriteString("func notificationTypeOf(n proto.Message) (uint16, bool) {\n\tswitch n.(type) {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("\tcase *pb.%s:\n\t\treturn uint16(pb.Type_%s), true\n", n.MessageType, n.EnumName))
	}
	b.WriteString("\tdefault:\n\t\treturn 0, false\n\t}\n}\n")

	return format.Source([]byte(b.String()))
}
