package protocolgen

import (
	"fmt"
	"sort"
	"strings"
)

const tsGeneratedHeader = "// SPDX-License-Identifier: Apache-2.0\n// Code generated by protocolgen; DO NOT EDIT.\n"

// GenTSActions 生成出方向 action 无状态函数。
// 不生成 ActionApi interface、不生成 class、不生成 SDK 公开接口、不生成 msg_id。
func GenTSActions(m *Manifest) []byte {
	var b strings.Builder
	b.WriteString(tsGeneratedHeader)
	b.WriteString("//\n// TS action 是出方向：SDK 主动调用服务端。每个函数只负责\n")
	b.WriteString("// Type + RequestCodec + ResponseCodec + transport.sendBinary，不做参数校验、\n")
	b.WriteString("// 缓存、事件、状态机、分页规则或 msg_id 生成。SDK 公开接口继续手写并调用这些函数。\n\n")

	names := map[string]bool{}
	for _, a := range m.Actions {
		names[a.RequestMessage] = true
		names[a.ResponseMessage] = true
	}
	b.WriteString("import type { ClientTransport } from '../transport/connection';\n")
	b.WriteString("import { sendProtoAction } from '../internal/codec';\n")
	b.WriteString(tsImportBlock(names))
	b.WriteString("\n")

	for _, a := range m.Actions {
		b.WriteString(fmt.Sprintf("export function %s(\n", a.TSFunction))
		b.WriteString("  transport: ClientTransport,\n")
		b.WriteString(fmt.Sprintf("  req: %s,\n", a.RequestMessage))
		b.WriteString(fmt.Sprintf("): Promise<%s> {\n", a.ResponseMessage))
		b.WriteString("  return sendProtoAction(\n")
		b.WriteString("    transport,\n")
		b.WriteString(fmt.Sprintf("    Type.%s,\n", a.EnumName))
		b.WriteString(fmt.Sprintf("    %s,\n", a.RequestMessage))
		b.WriteString("    req,\n")
		b.WriteString(fmt.Sprintf("    %s,\n", a.ResponseMessage))
		b.WriteString("  );\n}\n\n")
	}
	return []byte(b.String())
}

// GenTSNotifications 生成入方向 NotificationHandler 接口与 dispatchNotificationFrame。
func GenTSNotifications(m *Manifest) []byte {
	var b strings.Builder
	b.WriteString(tsGeneratedHeader)
	b.WriteString("//\n// TS notification 是入方向：服务端推 frame 过来。这里生成强类型 handler 接口\n")
	b.WriteString("// 和 frame 分发；方法不可选，新增通知后 SDK 内部 handler 未实现即编译失败。\n\n")

	names := map[string]bool{}
	for _, n := range m.Notifications {
		names[n.MessageType] = true
	}
	b.WriteString("import type { Frame } from '../transport/frame';\n")
	b.WriteString(tsImportBlock(names))
	b.WriteString("\n")

	// NotificationHandler interface。
	b.WriteString("export interface NotificationHandler {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("  /** %s：%s */\n", n.Name, n.Desc))
		b.WriteString(fmt.Sprintf("  %s(n: %s): void | Promise<void>;\n", n.TSHandlerMethod, n.MessageType))
	}
	b.WriteString("}\n\n")

	// 分发结果类型。
	b.WriteString(`export type NotificationDispatchResult =
  | { ok: true; handled: true; typeId: number }
  | { ok: true; handled: false }
  | { ok: false; handled: false; typeId: number; error: Error };

`)

	// dispatchNotificationFrame。
	b.WriteString("export async function dispatchNotificationFrame(\n")
	b.WriteString("  handler: NotificationHandler,\n")
	b.WriteString("  frame: Frame,\n")
	b.WriteString("): Promise<NotificationDispatchResult> {\n")
	b.WriteString("  if (frame.requestId !== '0') return { ok: true, handled: false };\n")
	b.WriteString("  switch (frame.typeId) {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("    case Type.%s: {\n", n.EnumName))
		b.WriteString("      try {\n")
		b.WriteString(fmt.Sprintf("        const n = %s.decode(frame.body);\n", n.MessageType))
		b.WriteString(fmt.Sprintf("        await handler.%s(n);\n", n.TSHandlerMethod))
		b.WriteString("        return { ok: true, handled: true, typeId: frame.typeId };\n")
		b.WriteString("      } catch (err) {\n")
		b.WriteString("        return { ok: false, handled: false, typeId: frame.typeId, error: err instanceof Error ? err : new Error(String(err)) };\n")
		b.WriteString("      }\n")
		b.WriteString("    }\n")
	}
	b.WriteString("    default:\n")
	b.WriteString("      return { ok: true, handled: false };\n")
	b.WriteString("  }\n}\n\n")

	// NoopNotificationHandler。
	b.WriteString("// NoopNotificationHandler 提供空实现，便于测试或可选处理；SDK 核心不得依赖它掩盖漏处理。\n")
	b.WriteString("export class NoopNotificationHandler implements NotificationHandler {\n")
	for _, n := range m.Notifications {
		b.WriteString(fmt.Sprintf("  %s(): void {}\n", n.TSHandlerMethod))
	}
	b.WriteString("}\n")
	return []byte(b.String())
}

func tsImportBlock(names map[string]bool) string {
	sorted := make([]string, 0, len(names)+1)
	sorted = append(sorted, "Type")
	for name := range names {
		sorted = append(sorted, name)
	}
	sort.Strings(sorted)
	var b strings.Builder
	b.WriteString("import {\n")
	for _, name := range sorted {
		b.WriteString(fmt.Sprintf("  %s,\n", name))
	}
	b.WriteString("} from '@yimsg/protocol';\n")
	return b.String()
}
