package appmsg

const (
	ActionAcceptFriend       = "accept_friend"
	ActionAddFriend          = "add_friend"
	ActionAddGroupMember     = "add_group_member"
	ActionAuthenticate       = "authenticate"
	ActionBlockUser          = "block_user"
	ActionCreateGroup        = "create_group"
	ActionDeleteConversation = "delete_conversation"
	ActionDeleteFriend       = "delete_friend"
	ActionDeleteMessage      = "delete_message"
	ActionFavoriteGroup      = "favorite_group"
	ActionGetBlocklist       = "get_blocklist"
	ActionGetContacts        = "get_contacts"
	ActionGetConversations   = "get_conversations"
	ActionGetGroupInfos      = "get_group_infos"
	ActionGetGroupMembers    = "get_group_members"
	ActionGetMessages        = "get_messages"
	ActionGetMutelist        = "get_mutelist"
	ActionGetContactCount    = "get_contact_count"
	ActionGetUnreadCount     = "get_unread_count"
	ActionGetUserInfos       = "get_user_infos"
	ActionLogin              = "login"
	ActionLogout             = "logout"
	ActionClearUnread        = "clear_unread"
	ActionMuteConversation   = "mute_conversation"
	ActionPing               = "ping"
	ActionRegister           = "register"
	ActionRejectFriend       = "reject_friend"
	ActionRemoveGroupMember  = "remove_group_member"
	ActionSearchUser         = "search_user"
	ActionSendMessage        = "send_message"
	ActionSyncBlocklist      = "sync_blocklist"
	ActionSyncContacts       = "sync_contacts"
	ActionSyncConversations  = "sync_conversations"
	ActionSyncMessages       = "sync_messages"
	ActionSyncMutelist       = "sync_mutelist"
	ActionUnblockUser        = "unblock_user"
	ActionUnfavoriteGroup    = "unfavorite_group"
	ActionUnmuteConversation = "unmute_conversation"
	ActionUpdateGroupInfo    = "update_group_info"
	ActionUpdatePassword     = "update_password"
	ActionUpdateRemark       = "update_remark"
	ActionUpdateUserInfo     = "update_user_info"
)
